"""add linkedin connections table

Revision ID: 4e741f4caaef
Revises: d30b90cdf120
Create Date: 2026-06-25 19:52:45.429791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e741f4caaef'
down_revision: Union[str, Sequence[str], None] = 'd30b90cdf120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'linkedin_connections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column('company', sa.String(length=255), nullable=True),
        sa.Column('position', sa.String(length=255), nullable=True),
        sa.Column('connected_on', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_linkedin_connections_company', 'linkedin_connections', ['company'], unique=False)
    op.create_index('ix_linkedin_connections_id', 'linkedin_connections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_linkedin_connections_id', table_name='linkedin_connections')
    op.drop_index('ix_linkedin_connections_company', table_name='linkedin_connections')
    op.drop_table('linkedin_connections')
    # ### end Alembic commands ###