"""create match cache table

Revision ID: d30b90cdf120
Revises: bd1ac0a13ce9
Create Date: 2026-06-22 23:30:57.854006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30b90cdf120'
down_revision: Union[str, Sequence[str], None] = 'bd1ac0a13ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('cached_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_cache_id'), 'match_cache', ['id'], unique=False)
    op.create_index(op.f('ix_match_cache_payload_hash'), 'match_cache', ['payload_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_cache_payload_hash'), table_name='match_cache')
    op.drop_index(op.f('ix_match_cache_id'), table_name='match_cache')
    op.drop_table('match_cache')
    # ### end Alembic commands ###
